/*
 * generated by Xtext
 */
package dk.itu.mdd.configurator.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ConfGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cRootAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cRootFeature_ImplParserRuleCall_0 = (RuleCall)cRootAssignment.eContents().get(0);
		
		//Model:
		//	root=Feature_Impl;
		@Override public ParserRule getRule() { return rule; }

		//root=Feature_Impl
		public Assignment getRootAssignment() { return cRootAssignment; }

		//Feature_Impl
		public RuleCall getRootFeature_ImplParserRuleCall_0() { return cRootFeature_ImplParserRuleCall_0; }
	}

	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Feature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFeature_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGroupedParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMandatoryParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cOptionalParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Feature:
		//	Feature_Impl | Grouped | Mandatory | Optional;
		@Override public ParserRule getRule() { return rule; }

		//Feature_Impl | Grouped | Mandatory | Optional
		public Alternatives getAlternatives() { return cAlternatives; }

		//Feature_Impl
		public RuleCall getFeature_ImplParserRuleCall_0() { return cFeature_ImplParserRuleCall_0; }

		//Grouped
		public RuleCall getGroupedParserRuleCall_1() { return cGroupedParserRuleCall_1; }

		//Mandatory
		public RuleCall getMandatoryParserRuleCall_2() { return cMandatoryParserRuleCall_2; }

		//Optional
		public RuleCall getOptionalParserRuleCall_3() { return cOptionalParserRuleCall_3; }
	}

	public class SolitaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Solitary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMandatoryParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOptionalParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Solitary:
		//	Mandatory | Optional;
		@Override public ParserRule getRule() { return rule; }

		//Mandatory | Optional
		public Alternatives getAlternatives() { return cAlternatives; }

		//Mandatory
		public RuleCall getMandatoryParserRuleCall_0() { return cMandatoryParserRuleCall_0; }

		//Optional
		public RuleCall getOptionalParserRuleCall_1() { return cOptionalParserRuleCall_1; }
	}

	public class ConstrainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constrain");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cConjunctionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftExpAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorDisjunctiveOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExpAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExpConjunctionParserRuleCall_1_2_0 = (RuleCall)cRightExpAssignment_1_2.eContents().get(0);
		
		////Binary | Unary;
		//Constrain:
		//	Conjunction ({Binary.leftExp=current} Operator=DisjunctiveOperator rightExp=Conjunction)*;
		@Override public ParserRule getRule() { return rule; }

		//Conjunction ({Binary.leftExp=current} Operator=DisjunctiveOperator rightExp=Conjunction)*
		public Group getGroup() { return cGroup; }

		//Conjunction
		public RuleCall getConjunctionParserRuleCall_0() { return cConjunctionParserRuleCall_0; }

		//({Binary.leftExp=current} Operator=DisjunctiveOperator rightExp=Conjunction)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.leftExp=current}
		public Action getBinaryLeftExpAction_1_0() { return cBinaryLeftExpAction_1_0; }

		//Operator=DisjunctiveOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//DisjunctiveOperator
		public RuleCall getOperatorDisjunctiveOperatorEnumRuleCall_1_1_0() { return cOperatorDisjunctiveOperatorEnumRuleCall_1_1_0; }

		//rightExp=Conjunction
		public Assignment getRightExpAssignment_1_2() { return cRightExpAssignment_1_2; }

		//Conjunction
		public RuleCall getRightExpConjunctionParserRuleCall_1_2_0() { return cRightExpConjunctionParserRuleCall_1_2_0; }
	}

	public class ConjunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Conjunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cEqualityParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftExpAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorConjunctiveOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExpAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExpEqualityParserRuleCall_1_2_0 = (RuleCall)cRightExpAssignment_1_2.eContents().get(0);
		
		//Conjunction returns Constrain:
		//	Equality ({Binary.leftExp=current} Operator=ConjunctiveOperator rightExp=Equality)*;
		@Override public ParserRule getRule() { return rule; }

		//Equality ({Binary.leftExp=current} Operator=ConjunctiveOperator rightExp=Equality)*
		public Group getGroup() { return cGroup; }

		//Equality
		public RuleCall getEqualityParserRuleCall_0() { return cEqualityParserRuleCall_0; }

		//({Binary.leftExp=current} Operator=ConjunctiveOperator rightExp=Equality)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.leftExp=current}
		public Action getBinaryLeftExpAction_1_0() { return cBinaryLeftExpAction_1_0; }

		//Operator=ConjunctiveOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//ConjunctiveOperator
		public RuleCall getOperatorConjunctiveOperatorEnumRuleCall_1_1_0() { return cOperatorConjunctiveOperatorEnumRuleCall_1_1_0; }

		//rightExp=Equality
		public Assignment getRightExpAssignment_1_2() { return cRightExpAssignment_1_2; }

		//Equality
		public RuleCall getRightExpEqualityParserRuleCall_1_2_0() { return cRightExpEqualityParserRuleCall_1_2_0; }
	}

	public class EqualityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Equality");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cComparisonParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftExpAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorEqualityOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExpAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExpComparisonParserRuleCall_1_2_0 = (RuleCall)cRightExpAssignment_1_2.eContents().get(0);
		
		//Equality returns Constrain:
		//	Comparison ({Binary.leftExp=current} Operator=EqualityOperator rightExp=Comparison)*;
		@Override public ParserRule getRule() { return rule; }

		//Comparison ({Binary.leftExp=current} Operator=EqualityOperator rightExp=Comparison)*
		public Group getGroup() { return cGroup; }

		//Comparison
		public RuleCall getComparisonParserRuleCall_0() { return cComparisonParserRuleCall_0; }

		//({Binary.leftExp=current} Operator=EqualityOperator rightExp=Comparison)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.leftExp=current}
		public Action getBinaryLeftExpAction_1_0() { return cBinaryLeftExpAction_1_0; }

		//Operator=EqualityOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//EqualityOperator
		public RuleCall getOperatorEqualityOperatorEnumRuleCall_1_1_0() { return cOperatorEqualityOperatorEnumRuleCall_1_1_0; }

		//rightExp=Comparison
		public Assignment getRightExpAssignment_1_2() { return cRightExpAssignment_1_2; }

		//Comparison
		public RuleCall getRightExpComparisonParserRuleCall_1_2_0() { return cRightExpComparisonParserRuleCall_1_2_0; }
	}

	public class ComparisonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Comparison");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBinaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftExpAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorComparativeOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExpAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExpBinaryParserRuleCall_1_2_0 = (RuleCall)cRightExpAssignment_1_2.eContents().get(0);
		
		//Comparison returns Constrain:
		//	Binary ({Binary.leftExp=current} Operator=ComparativeOperator rightExp=Binary)*;
		@Override public ParserRule getRule() { return rule; }

		//Binary ({Binary.leftExp=current} Operator=ComparativeOperator rightExp=Binary)*
		public Group getGroup() { return cGroup; }

		//Binary
		public RuleCall getBinaryParserRuleCall_0() { return cBinaryParserRuleCall_0; }

		//({Binary.leftExp=current} Operator=ComparativeOperator rightExp=Binary)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.leftExp=current}
		public Action getBinaryLeftExpAction_1_0() { return cBinaryLeftExpAction_1_0; }

		//Operator=ComparativeOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//ComparativeOperator
		public RuleCall getOperatorComparativeOperatorEnumRuleCall_1_1_0() { return cOperatorComparativeOperatorEnumRuleCall_1_1_0; }

		//rightExp=Binary
		public Assignment getRightExpAssignment_1_2() { return cRightExpAssignment_1_2; }

		//Binary
		public RuleCall getRightExpBinaryParserRuleCall_1_2_0() { return cRightExpBinaryParserRuleCall_1_2_0; }
	}

	public class BinaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Binary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftExpAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cRightExpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightExpPrimaryParserRuleCall_1_1_0 = (RuleCall)cRightExpAssignment_1_1.eContents().get(0);
		
		//Binary returns Constrain:
		//	Primary ({Binary.leftExp=current} rightExp=Primary)*;
		@Override public ParserRule getRule() { return rule; }

		//Primary ({Binary.leftExp=current} rightExp=Primary)*
		public Group getGroup() { return cGroup; }

		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }

		//({Binary.leftExp=current} rightExp=Primary)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.leftExp=current}
		public Action getBinaryLeftExpAction_1_0() { return cBinaryLeftExpAction_1_0; }

		//rightExp=Primary
		public Assignment getRightExpAssignment_1_1() { return cRightExpAssignment_1_1; }

		//Primary
		public RuleCall getRightExpPrimaryParserRuleCall_1_1_0() { return cRightExpPrimaryParserRuleCall_1_1_0; }
	}

	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cFeatureReferenceAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final CrossReference cFeatureReferenceGroupedCrossReference_0_0 = (CrossReference)cFeatureReferenceAssignment_0.eContents().get(0);
		private final RuleCall cFeatureReferenceGroupedQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cFeatureReferenceGroupedCrossReference_0_0.eContents().get(1);
		private final RuleCall cUnaryParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cConstrainParserRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//Primary returns Constrain:
		//	featureReference=[Grouped|QualifiedName] | Unary | "(" Constrain ")";
		@Override public ParserRule getRule() { return rule; }

		//featureReference=[Grouped|QualifiedName] | Unary | "(" Constrain ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//featureReference=[Grouped|QualifiedName]
		public Assignment getFeatureReferenceAssignment_0() { return cFeatureReferenceAssignment_0; }

		//[Grouped|QualifiedName]
		public CrossReference getFeatureReferenceGroupedCrossReference_0_0() { return cFeatureReferenceGroupedCrossReference_0_0; }

		//QualifiedName
		public RuleCall getFeatureReferenceGroupedQualifiedNameParserRuleCall_0_0_1() { return cFeatureReferenceGroupedQualifiedNameParserRuleCall_0_0_1; }

		//Unary
		public RuleCall getUnaryParserRuleCall_1() { return cUnaryParserRuleCall_1; }

		//"(" Constrain ")"
		public Group getGroup_2() { return cGroup_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }

		//Constrain
		public RuleCall getConstrainParserRuleCall_2_1() { return cConstrainParserRuleCall_2_1; }

		//")"
		public Keyword getRightParenthesisKeyword_2_2() { return cRightParenthesisKeyword_2_2; }
	}

	public class UnaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Unary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUnaryAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cOperatorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cOperatorAlternatives_1_0 = (Alternatives)cOperatorAssignment_1.eContents().get(0);
		private final Keyword cOperatorExclamationMarkKeyword_1_0_0 = (Keyword)cOperatorAlternatives_1_0.eContents().get(0);
		private final Keyword cOperatorHyphenMinusKeyword_1_0_1 = (Keyword)cOperatorAlternatives_1_0.eContents().get(1);
		private final Assignment cExpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpPrimaryParserRuleCall_2_0 = (RuleCall)cExpAssignment_2.eContents().get(0);
		
		//Unary returns Constrain:
		//	{Unary} Operator=("!" | "-") exp=Primary;
		@Override public ParserRule getRule() { return rule; }

		//{Unary} Operator=("!" | "-") exp=Primary
		public Group getGroup() { return cGroup; }

		//{Unary}
		public Action getUnaryAction_0() { return cUnaryAction_0; }

		//Operator=("!" | "-")
		public Assignment getOperatorAssignment_1() { return cOperatorAssignment_1; }

		//"!" | "-"
		public Alternatives getOperatorAlternatives_1_0() { return cOperatorAlternatives_1_0; }

		//"!"
		public Keyword getOperatorExclamationMarkKeyword_1_0_0() { return cOperatorExclamationMarkKeyword_1_0_0; }

		//"-"
		public Keyword getOperatorHyphenMinusKeyword_1_0_1() { return cOperatorHyphenMinusKeyword_1_0_1; }

		//exp=Primary
		public Assignment getExpAssignment_2() { return cExpAssignment_2; }

		//Primary
		public RuleCall getExpPrimaryParserRuleCall_2_0() { return cExpPrimaryParserRuleCall_2_0; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		@Override public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class GroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Group");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOrParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cXorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Group:
		//	Or | Xor;
		@Override public ParserRule getRule() { return rule; }

		//Or | Xor
		public Alternatives getAlternatives() { return cAlternatives; }

		//Or
		public RuleCall getOrParserRuleCall_0() { return cOrParserRuleCall_0; }

		//Xor
		public RuleCall getXorParserRuleCall_1() { return cXorParserRuleCall_1; }
	}

	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Attribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCStringParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNumberParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRangeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCBooleanParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Attribute:
		//	CString | Number | Range | CBoolean;
		@Override public ParserRule getRule() { return rule; }

		//CString | Number | Range | CBoolean
		public Alternatives getAlternatives() { return cAlternatives; }

		//CString
		public RuleCall getCStringParserRuleCall_0() { return cCStringParserRuleCall_0; }

		//Number
		public RuleCall getNumberParserRuleCall_1() { return cNumberParserRuleCall_1; }

		//Range
		public RuleCall getRangeParserRuleCall_2() { return cRangeParserRuleCall_2; }

		//CBoolean
		public RuleCall getCBooleanParserRuleCall_3() { return cCBooleanParserRuleCall_3; }
	}

	public class RangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Range");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLowerAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLowerINTTerminalRuleCall_0_0 = (RuleCall)cLowerAssignment_0.eContents().get(0);
		private final Assignment cUpperAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUpperINTTerminalRuleCall_1_0 = (RuleCall)cUpperAssignment_1.eContents().get(0);
		
		////maybe this should return a constrain? just syntactic sugar, desugaring to leftExp > value < rightExp
		//Range:
		//	lower=INT upper=INT;
		@Override public ParserRule getRule() { return rule; }

		//lower=INT upper=INT
		public Group getGroup() { return cGroup; }

		//lower=INT
		public Assignment getLowerAssignment_0() { return cLowerAssignment_0; }

		//INT
		public RuleCall getLowerINTTerminalRuleCall_0_0() { return cLowerINTTerminalRuleCall_0_0; }

		//upper=INT
		public Assignment getUpperAssignment_1() { return cUpperAssignment_1; }

		//INT
		public RuleCall getUpperINTTerminalRuleCall_1_0() { return cUpperINTTerminalRuleCall_1_0; }
	}

	public class CStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CString");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//CString:
		//	value=EString;
		@Override public ParserRule getRule() { return rule; }

		//value=EString
		public Assignment getValueAssignment() { return cValueAssignment; }

		//EString
		public RuleCall getValueEStringParserRuleCall_0() { return cValueEStringParserRuleCall_0; }
	}

	public class CBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CBoolean");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueBOOLEANTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//CBoolean:
		//	value=BOOLEAN;
		@Override public ParserRule getRule() { return rule; }

		//value=BOOLEAN
		public Assignment getValueAssignment() { return cValueAssignment; }

		//BOOLEAN
		public RuleCall getValueBOOLEANTerminalRuleCall_0() { return cValueBOOLEANTerminalRuleCall_0; }
	}

	public class NumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Number");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Number:
		//	value=INT;
		@Override public ParserRule getRule() { return rule; }

		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNULLTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	ID | NULL;
		@Override public ParserRule getRule() { return rule; }

		//ID | NULL
		public Alternatives getAlternatives() { return cAlternatives; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//NULL
		public RuleCall getNULLTerminalRuleCall_1() { return cNULLTerminalRuleCall_1; }
	}

	public class Feature_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Feature_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFeatureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final RuleCall cBEGINTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cSubfeatureAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSubfeatureSolitaryParserRuleCall_2_1_0 = (RuleCall)cSubfeatureAssignment_2_1.eContents().get(0);
		private final Assignment cSubfeatureAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cSubfeatureSolitaryParserRuleCall_2_2_0 = (RuleCall)cSubfeatureAssignment_2_2.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_2_3 = (RuleCall)cGroup_2.eContents().get(3);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cConstrainsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_3_1_0 = (RuleCall)cConstrainsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cConstrainsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_3_2_1_0 = (RuleCall)cConstrainsAssignment_3_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		
		////('att' attributes+=Attribute ( "," attributes+=Attribute)* )?
		//Feature_Impl returns Feature:
		//	"Feature" name=EString (BEGIN subfeature+=Solitary subfeature+=Solitary* END)? ("[" constrains+=Constrain (","
		//	constrains+=Constrain)* "]")?;
		@Override public ParserRule getRule() { return rule; }

		//"Feature" name=EString (BEGIN subfeature+=Solitary subfeature+=Solitary* END)? ("[" constrains+=Constrain (","
		//constrains+=Constrain)* "]")?
		public Group getGroup() { return cGroup; }

		//"Feature"
		public Keyword getFeatureKeyword_0() { return cFeatureKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//(BEGIN subfeature+=Solitary subfeature+=Solitary* END)?
		public Group getGroup_2() { return cGroup_2; }

		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2_0() { return cBEGINTerminalRuleCall_2_0; }

		//subfeature+=Solitary
		public Assignment getSubfeatureAssignment_2_1() { return cSubfeatureAssignment_2_1; }

		//Solitary
		public RuleCall getSubfeatureSolitaryParserRuleCall_2_1_0() { return cSubfeatureSolitaryParserRuleCall_2_1_0; }

		//subfeature+=Solitary*
		public Assignment getSubfeatureAssignment_2_2() { return cSubfeatureAssignment_2_2; }

		//Solitary
		public RuleCall getSubfeatureSolitaryParserRuleCall_2_2_0() { return cSubfeatureSolitaryParserRuleCall_2_2_0; }

		//END
		public RuleCall getENDTerminalRuleCall_2_3() { return cENDTerminalRuleCall_2_3; }

		//("[" constrains+=Constrain ("," constrains+=Constrain)* "]")?
		public Group getGroup_3() { return cGroup_3; }

		//"["
		public Keyword getLeftSquareBracketKeyword_3_0() { return cLeftSquareBracketKeyword_3_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_3_1() { return cConstrainsAssignment_3_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_3_1_0() { return cConstrainsConstrainParserRuleCall_3_1_0; }

		//("," constrains+=Constrain)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_3_2_1() { return cConstrainsAssignment_3_2_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_3_2_1_0() { return cConstrainsConstrainParserRuleCall_3_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3_3() { return cRightSquareBracketKeyword_3_3; }
	}

	public class GroupedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Grouped");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAttributesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_1_1_0 = (RuleCall)cAttributesAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cAttributesAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_1_2_1_0 = (RuleCall)cAttributesAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cConstrainsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_2_1_0 = (RuleCall)cConstrainsAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cConstrainsAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_2_2_1_0 = (RuleCall)cConstrainsAssignment_2_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//Grouped:
		//	name=EString ("(" attributes+=Attribute ("," attributes+=Attribute)* ")")? ("[" constrains+=Constrain (","
		//	constrains+=Constrain)* "]")?;
		@Override public ParserRule getRule() { return rule; }

		//name=EString ("(" attributes+=Attribute ("," attributes+=Attribute)* ")")? ("[" constrains+=Constrain (","
		//constrains+=Constrain)* "]")?
		public Group getGroup() { return cGroup; }

		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }

		//("(" attributes+=Attribute ("," attributes+=Attribute)* ")")?
		public Group getGroup_1() { return cGroup_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_1_1() { return cAttributesAssignment_1_1; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_1_1_0() { return cAttributesAttributeParserRuleCall_1_1_0; }

		//("," attributes+=Attribute)*
		public Group getGroup_1_2() { return cGroup_1_2; }

		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }

		//attributes+=Attribute
		public Assignment getAttributesAssignment_1_2_1() { return cAttributesAssignment_1_2_1; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_1_2_1_0() { return cAttributesAttributeParserRuleCall_1_2_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }

		//("[" constrains+=Constrain ("," constrains+=Constrain)* "]")?
		public Group getGroup_2() { return cGroup_2; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_2_1() { return cConstrainsAssignment_2_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_2_1_0() { return cConstrainsConstrainParserRuleCall_2_1_0; }

		//("," constrains+=Constrain)*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//","
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_2_2_1() { return cConstrainsAssignment_2_2_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_2_2_1_0() { return cConstrainsConstrainParserRuleCall_2_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2_3() { return cRightSquareBracketKeyword_2_3; }
	}

	public class MandatoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Mandatory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cSubfeatureAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cSubfeatureSolitaryParserRuleCall_1_1_0 = (RuleCall)cSubfeatureAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cSubfeatureAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cSubfeatureSolitaryParserRuleCall_1_2_1_0 = (RuleCall)cSubfeatureAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cConstrainsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_2_1_0 = (RuleCall)cConstrainsAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cConstrainsAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_2_2_1_0 = (RuleCall)cConstrainsAssignment_2_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cGroupsAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cGroupsGroupParserRuleCall_3_0_0 = (RuleCall)cGroupsAssignment_3_0.eContents().get(0);
		private final Assignment cGroupsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cGroupsGroupParserRuleCall_3_1_0 = (RuleCall)cGroupsAssignment_3_1.eContents().get(0);
		
		//Mandatory:
		//	name=EString ("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")? ("[" constrains+=Constrain (","
		//	constrains+=Constrain)* "]")? (groups+=Group groups+=Group*)?;
		@Override public ParserRule getRule() { return rule; }

		//name=EString ("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")? ("[" constrains+=Constrain (","
		//constrains+=Constrain)* "]")? (groups+=Group groups+=Group*)?
		public Group getGroup() { return cGroup; }

		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }

		//("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")?
		public Group getGroup_1() { return cGroup_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }

		//subfeature+=Solitary
		public Assignment getSubfeatureAssignment_1_1() { return cSubfeatureAssignment_1_1; }

		//Solitary
		public RuleCall getSubfeatureSolitaryParserRuleCall_1_1_0() { return cSubfeatureSolitaryParserRuleCall_1_1_0; }

		//("," subfeature+=Solitary)*
		public Group getGroup_1_2() { return cGroup_1_2; }

		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }

		//subfeature+=Solitary
		public Assignment getSubfeatureAssignment_1_2_1() { return cSubfeatureAssignment_1_2_1; }

		//Solitary
		public RuleCall getSubfeatureSolitaryParserRuleCall_1_2_1_0() { return cSubfeatureSolitaryParserRuleCall_1_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_3() { return cRightCurlyBracketKeyword_1_3; }

		//("[" constrains+=Constrain ("," constrains+=Constrain)* "]")?
		public Group getGroup_2() { return cGroup_2; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_2_1() { return cConstrainsAssignment_2_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_2_1_0() { return cConstrainsConstrainParserRuleCall_2_1_0; }

		//("," constrains+=Constrain)*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//","
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_2_2_1() { return cConstrainsAssignment_2_2_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_2_2_1_0() { return cConstrainsConstrainParserRuleCall_2_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2_3() { return cRightSquareBracketKeyword_2_3; }

		//(groups+=Group groups+=Group*)?
		public Group getGroup_3() { return cGroup_3; }

		//groups+=Group
		public Assignment getGroupsAssignment_3_0() { return cGroupsAssignment_3_0; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_3_0_0() { return cGroupsGroupParserRuleCall_3_0_0; }

		//groups+=Group*
		public Assignment getGroupsAssignment_3_1() { return cGroupsAssignment_3_1; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_3_1_0() { return cGroupsGroupParserRuleCall_3_1_0; }
	}

	public class OptionalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Optional");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuestionMarkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSubfeatureAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSubfeatureSolitaryParserRuleCall_2_1_0 = (RuleCall)cSubfeatureAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cSubfeatureAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cSubfeatureSolitaryParserRuleCall_2_2_1_0 = (RuleCall)cSubfeatureAssignment_2_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cConstrainsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_3_1_0 = (RuleCall)cConstrainsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cConstrainsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cConstrainsConstrainParserRuleCall_3_2_1_0 = (RuleCall)cConstrainsAssignment_3_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cGroupsAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cGroupsGroupParserRuleCall_4_0_0 = (RuleCall)cGroupsAssignment_4_0.eContents().get(0);
		private final Assignment cGroupsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cGroupsGroupParserRuleCall_4_1_0 = (RuleCall)cGroupsAssignment_4_1.eContents().get(0);
		
		//Optional:
		//	"?" name=EString ("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")? ("[" constrains+=Constrain (","
		//	constrains+=Constrain)* "]")? (groups+=Group groups+=Group*)?;
		@Override public ParserRule getRule() { return rule; }

		//"?" name=EString ("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")? ("[" constrains+=Constrain (","
		//constrains+=Constrain)* "]")? (groups+=Group groups+=Group*)?
		public Group getGroup() { return cGroup; }

		//"?"
		public Keyword getQuestionMarkKeyword_0() { return cQuestionMarkKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }

		//subfeature+=Solitary
		public Assignment getSubfeatureAssignment_2_1() { return cSubfeatureAssignment_2_1; }

		//Solitary
		public RuleCall getSubfeatureSolitaryParserRuleCall_2_1_0() { return cSubfeatureSolitaryParserRuleCall_2_1_0; }

		//("," subfeature+=Solitary)*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//","
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }

		//subfeature+=Solitary
		public Assignment getSubfeatureAssignment_2_2_1() { return cSubfeatureAssignment_2_2_1; }

		//Solitary
		public RuleCall getSubfeatureSolitaryParserRuleCall_2_2_1_0() { return cSubfeatureSolitaryParserRuleCall_2_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }

		//("[" constrains+=Constrain ("," constrains+=Constrain)* "]")?
		public Group getGroup_3() { return cGroup_3; }

		//"["
		public Keyword getLeftSquareBracketKeyword_3_0() { return cLeftSquareBracketKeyword_3_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_3_1() { return cConstrainsAssignment_3_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_3_1_0() { return cConstrainsConstrainParserRuleCall_3_1_0; }

		//("," constrains+=Constrain)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//constrains+=Constrain
		public Assignment getConstrainsAssignment_3_2_1() { return cConstrainsAssignment_3_2_1; }

		//Constrain
		public RuleCall getConstrainsConstrainParserRuleCall_3_2_1_0() { return cConstrainsConstrainParserRuleCall_3_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3_3() { return cRightSquareBracketKeyword_3_3; }

		//(groups+=Group groups+=Group*)?
		public Group getGroup_4() { return cGroup_4; }

		//groups+=Group
		public Assignment getGroupsAssignment_4_0() { return cGroupsAssignment_4_0; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_4_0_0() { return cGroupsGroupParserRuleCall_4_0_0; }

		//groups+=Group*
		public Assignment getGroupsAssignment_4_1() { return cGroupsAssignment_4_1; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_4_1_0() { return cGroupsGroupParserRuleCall_4_1_0; }
	}

	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOrKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final RuleCall cBEGINTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cGroupedAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cGroupedGroupedParserRuleCall_2_1_0 = (RuleCall)cGroupedAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cGroupedAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cGroupedGroupedParserRuleCall_2_2_1_0 = (RuleCall)cGroupedAssignment_2_2_1.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_2_3 = (RuleCall)cGroup_2.eContents().get(3);
		
		//Or:
		//	"Or" name=EString (BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?;
		@Override public ParserRule getRule() { return rule; }

		//"Or" name=EString (BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?
		public Group getGroup() { return cGroup; }

		//"Or"
		public Keyword getOrKeyword_0() { return cOrKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//(BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?
		public Group getGroup_2() { return cGroup_2; }

		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2_0() { return cBEGINTerminalRuleCall_2_0; }

		//grouped+=Grouped
		public Assignment getGroupedAssignment_2_1() { return cGroupedAssignment_2_1; }

		//Grouped
		public RuleCall getGroupedGroupedParserRuleCall_2_1_0() { return cGroupedGroupedParserRuleCall_2_1_0; }

		//(","* grouped+=Grouped)*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//","*
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }

		//grouped+=Grouped
		public Assignment getGroupedAssignment_2_2_1() { return cGroupedAssignment_2_2_1; }

		//Grouped
		public RuleCall getGroupedGroupedParserRuleCall_2_2_1_0() { return cGroupedGroupedParserRuleCall_2_2_1_0; }

		//END
		public RuleCall getENDTerminalRuleCall_2_3() { return cENDTerminalRuleCall_2_3; }
	}

	public class XorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Xor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cXorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final RuleCall cBEGINTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cGroupedAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cGroupedGroupedParserRuleCall_2_1_0 = (RuleCall)cGroupedAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cGroupedAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cGroupedGroupedParserRuleCall_2_2_1_0 = (RuleCall)cGroupedAssignment_2_2_1.eContents().get(0);
		private final RuleCall cENDTerminalRuleCall_2_3 = (RuleCall)cGroup_2.eContents().get(3);
		
		//Xor:
		//	"Xor" name=EString (BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?;
		@Override public ParserRule getRule() { return rule; }

		//"Xor" name=EString (BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?
		public Group getGroup() { return cGroup; }

		//"Xor"
		public Keyword getXorKeyword_0() { return cXorKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//(BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?
		public Group getGroup_2() { return cGroup_2; }

		//BEGIN
		public RuleCall getBEGINTerminalRuleCall_2_0() { return cBEGINTerminalRuleCall_2_0; }

		//grouped+=Grouped
		public Assignment getGroupedAssignment_2_1() { return cGroupedAssignment_2_1; }

		//Grouped
		public RuleCall getGroupedGroupedParserRuleCall_2_1_0() { return cGroupedGroupedParserRuleCall_2_1_0; }

		//(","* grouped+=Grouped)*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//","*
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }

		//grouped+=Grouped
		public Assignment getGroupedAssignment_2_2_1() { return cGroupedAssignment_2_2_1; }

		//Grouped
		public RuleCall getGroupedGroupedParserRuleCall_2_2_1_0() { return cGroupedGroupedParserRuleCall_2_2_1_0; }

		//END
		public RuleCall getENDTerminalRuleCall_2_3() { return cENDTerminalRuleCall_2_3; }
	}
	
	
	public class DisjunctiveOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "DisjunctiveOperator");
		private final EnumLiteralDeclaration cDisjunctionEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cDisjunctionVerticalLineVerticalLineKeyword_0 = (Keyword)cDisjunctionEnumLiteralDeclaration.eContents().get(0);
		
		//enum DisjunctiveOperator returns BinaryOperator:
		//	disjunction="||";
		public EnumRule getRule() { return rule; }

		//disjunction="||"
		public EnumLiteralDeclaration getDisjunctionEnumLiteralDeclaration() { return cDisjunctionEnumLiteralDeclaration; }

		//"||"
		public Keyword getDisjunctionVerticalLineVerticalLineKeyword_0() { return cDisjunctionVerticalLineVerticalLineKeyword_0; }
	}

	public class ConjunctiveOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ConjunctiveOperator");
		private final EnumLiteralDeclaration cConjunctionEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cConjunctionAmpersandAmpersandKeyword_0 = (Keyword)cConjunctionEnumLiteralDeclaration.eContents().get(0);
		
		//enum ConjunctiveOperator returns BinaryOperator:
		//	conjunction="&&";
		public EnumRule getRule() { return rule; }

		//conjunction="&&"
		public EnumLiteralDeclaration getConjunctionEnumLiteralDeclaration() { return cConjunctionEnumLiteralDeclaration; }

		//"&&"
		public Keyword getConjunctionAmpersandAmpersandKeyword_0() { return cConjunctionAmpersandAmpersandKeyword_0; }
	}

	public class EqualityOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "EqualityOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEqualsEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEqualsEqualsSignEqualsSignKeyword_0_0 = (Keyword)cEqualsEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNotEqualsEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNotEqualsExclamationMarkEqualsSignKeyword_1_0 = (Keyword)cNotEqualsEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum EqualityOperator returns BinaryOperator:
		//	equals="==" | notEquals="!=";
		public EnumRule getRule() { return rule; }

		//equals="==" | notEquals="!="
		public Alternatives getAlternatives() { return cAlternatives; }

		//equals="=="
		public EnumLiteralDeclaration getEqualsEnumLiteralDeclaration_0() { return cEqualsEnumLiteralDeclaration_0; }

		//"=="
		public Keyword getEqualsEqualsSignEqualsSignKeyword_0_0() { return cEqualsEqualsSignEqualsSignKeyword_0_0; }

		//notEquals="!="
		public EnumLiteralDeclaration getNotEqualsEnumLiteralDeclaration_1() { return cNotEqualsEnumLiteralDeclaration_1; }

		//"!="
		public Keyword getNotEqualsExclamationMarkEqualsSignKeyword_1_0() { return cNotEqualsExclamationMarkEqualsSignKeyword_1_0; }
	}

	public class ComparativeOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ComparativeOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGreaterThanEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGreaterThanGreaterThanSignKeyword_0_0 = (Keyword)cGreaterThanEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLessThanEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLessThanLessThanSignKeyword_1_0 = (Keyword)cLessThanEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cGreaterOrEqualsEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cGreaterOrEqualsGreaterThanSignEqualsSignKeyword_2_0 = (Keyword)cGreaterOrEqualsEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLessOrEqualsEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLessOrEqualsLessThanSignEqualsSignKeyword_3_0 = (Keyword)cLessOrEqualsEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ComparativeOperator returns BinaryOperator:
		//	greaterThan=">" | lessThan="<" | greaterOrEquals=">=" | lessOrEquals="<=";
		public EnumRule getRule() { return rule; }

		//greaterThan=">" | lessThan="<" | greaterOrEquals=">=" | lessOrEquals="<="
		public Alternatives getAlternatives() { return cAlternatives; }

		//greaterThan=">"
		public EnumLiteralDeclaration getGreaterThanEnumLiteralDeclaration_0() { return cGreaterThanEnumLiteralDeclaration_0; }

		//">"
		public Keyword getGreaterThanGreaterThanSignKeyword_0_0() { return cGreaterThanGreaterThanSignKeyword_0_0; }

		//lessThan="<"
		public EnumLiteralDeclaration getLessThanEnumLiteralDeclaration_1() { return cLessThanEnumLiteralDeclaration_1; }

		//"<"
		public Keyword getLessThanLessThanSignKeyword_1_0() { return cLessThanLessThanSignKeyword_1_0; }

		//greaterOrEquals=">="
		public EnumLiteralDeclaration getGreaterOrEqualsEnumLiteralDeclaration_2() { return cGreaterOrEqualsEnumLiteralDeclaration_2; }

		//">="
		public Keyword getGreaterOrEqualsGreaterThanSignEqualsSignKeyword_2_0() { return cGreaterOrEqualsGreaterThanSignEqualsSignKeyword_2_0; }

		//lessOrEquals="<="
		public EnumLiteralDeclaration getLessOrEqualsEnumLiteralDeclaration_3() { return cLessOrEqualsEnumLiteralDeclaration_3; }

		//"<="
		public Keyword getLessOrEqualsLessThanSignEqualsSignKeyword_3_0() { return cLessOrEqualsLessThanSignEqualsSignKeyword_3_0; }
	}
	
	private final ModelElements pModel;
	private final FeatureElements pFeature;
	private final SolitaryElements pSolitary;
	private final ConstrainElements pConstrain;
	private final ConjunctionElements pConjunction;
	private final EqualityElements pEquality;
	private final ComparisonElements pComparison;
	private final BinaryElements pBinary;
	private final PrimaryElements pPrimary;
	private final UnaryElements pUnary;
	private final QualifiedNameElements pQualifiedName;
	private final DisjunctiveOperatorElements unknownRuleDisjunctiveOperator;
	private final ConjunctiveOperatorElements unknownRuleConjunctiveOperator;
	private final EqualityOperatorElements unknownRuleEqualityOperator;
	private final ComparativeOperatorElements unknownRuleComparativeOperator;
	private final GroupElements pGroup;
	private final AttributeElements pAttribute;
	private final RangeElements pRange;
	private final CStringElements pCString;
	private final CBooleanElements pCBoolean;
	private final NumberElements pNumber;
	private final EStringElements pEString;
	private final Feature_ImplElements pFeature_Impl;
	private final GroupedElements pGrouped;
	private final MandatoryElements pMandatory;
	private final OptionalElements pOptional;
	private final OrElements pOr;
	private final XorElements pXor;
	private final TerminalRule tNULL;
	private final TerminalRule tBOOLEAN;
	private final TerminalRule tBEGIN;
	private final TerminalRule tEND;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ConfGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pFeature = new FeatureElements();
		this.pSolitary = new SolitaryElements();
		this.pConstrain = new ConstrainElements();
		this.pConjunction = new ConjunctionElements();
		this.pEquality = new EqualityElements();
		this.pComparison = new ComparisonElements();
		this.pBinary = new BinaryElements();
		this.pPrimary = new PrimaryElements();
		this.pUnary = new UnaryElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.unknownRuleDisjunctiveOperator = new DisjunctiveOperatorElements();
		this.unknownRuleConjunctiveOperator = new ConjunctiveOperatorElements();
		this.unknownRuleEqualityOperator = new EqualityOperatorElements();
		this.unknownRuleComparativeOperator = new ComparativeOperatorElements();
		this.pGroup = new GroupElements();
		this.pAttribute = new AttributeElements();
		this.pRange = new RangeElements();
		this.pCString = new CStringElements();
		this.pCBoolean = new CBooleanElements();
		this.pNumber = new NumberElements();
		this.pEString = new EStringElements();
		this.pFeature_Impl = new Feature_ImplElements();
		this.pGrouped = new GroupedElements();
		this.pMandatory = new MandatoryElements();
		this.pOptional = new OptionalElements();
		this.pOr = new OrElements();
		this.pXor = new XorElements();
		this.tNULL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NULL");
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "BOOLEAN");
		this.tBEGIN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "BEGIN");
		this.tEND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "END");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.itu.mdd.configurator.Conf".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	root=Feature_Impl;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Feature:
	//	Feature_Impl | Grouped | Mandatory | Optional;
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}

	//Solitary:
	//	Mandatory | Optional;
	public SolitaryElements getSolitaryAccess() {
		return pSolitary;
	}
	
	public ParserRule getSolitaryRule() {
		return getSolitaryAccess().getRule();
	}

	////Binary | Unary;
	//Constrain:
	//	Conjunction ({Binary.leftExp=current} Operator=DisjunctiveOperator rightExp=Conjunction)*;
	public ConstrainElements getConstrainAccess() {
		return pConstrain;
	}
	
	public ParserRule getConstrainRule() {
		return getConstrainAccess().getRule();
	}

	//Conjunction returns Constrain:
	//	Equality ({Binary.leftExp=current} Operator=ConjunctiveOperator rightExp=Equality)*;
	public ConjunctionElements getConjunctionAccess() {
		return pConjunction;
	}
	
	public ParserRule getConjunctionRule() {
		return getConjunctionAccess().getRule();
	}

	//Equality returns Constrain:
	//	Comparison ({Binary.leftExp=current} Operator=EqualityOperator rightExp=Comparison)*;
	public EqualityElements getEqualityAccess() {
		return pEquality;
	}
	
	public ParserRule getEqualityRule() {
		return getEqualityAccess().getRule();
	}

	//Comparison returns Constrain:
	//	Binary ({Binary.leftExp=current} Operator=ComparativeOperator rightExp=Binary)*;
	public ComparisonElements getComparisonAccess() {
		return pComparison;
	}
	
	public ParserRule getComparisonRule() {
		return getComparisonAccess().getRule();
	}

	//Binary returns Constrain:
	//	Primary ({Binary.leftExp=current} rightExp=Primary)*;
	public BinaryElements getBinaryAccess() {
		return pBinary;
	}
	
	public ParserRule getBinaryRule() {
		return getBinaryAccess().getRule();
	}

	//Primary returns Constrain:
	//	featureReference=[Grouped|QualifiedName] | Unary | "(" Constrain ")";
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}

	//Unary returns Constrain:
	//	{Unary} Operator=("!" | "-") exp=Primary;
	public UnaryElements getUnaryAccess() {
		return pUnary;
	}
	
	public ParserRule getUnaryRule() {
		return getUnaryAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//enum DisjunctiveOperator returns BinaryOperator:
	//	disjunction="||";
	public DisjunctiveOperatorElements getDisjunctiveOperatorAccess() {
		return unknownRuleDisjunctiveOperator;
	}
	
	public EnumRule getDisjunctiveOperatorRule() {
		return getDisjunctiveOperatorAccess().getRule();
	}

	//enum ConjunctiveOperator returns BinaryOperator:
	//	conjunction="&&";
	public ConjunctiveOperatorElements getConjunctiveOperatorAccess() {
		return unknownRuleConjunctiveOperator;
	}
	
	public EnumRule getConjunctiveOperatorRule() {
		return getConjunctiveOperatorAccess().getRule();
	}

	//enum EqualityOperator returns BinaryOperator:
	//	equals="==" | notEquals="!=";
	public EqualityOperatorElements getEqualityOperatorAccess() {
		return unknownRuleEqualityOperator;
	}
	
	public EnumRule getEqualityOperatorRule() {
		return getEqualityOperatorAccess().getRule();
	}

	//enum ComparativeOperator returns BinaryOperator:
	//	greaterThan=">" | lessThan="<" | greaterOrEquals=">=" | lessOrEquals="<=";
	public ComparativeOperatorElements getComparativeOperatorAccess() {
		return unknownRuleComparativeOperator;
	}
	
	public EnumRule getComparativeOperatorRule() {
		return getComparativeOperatorAccess().getRule();
	}

	//Group:
	//	Or | Xor;
	public GroupElements getGroupAccess() {
		return pGroup;
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}

	//Attribute:
	//	CString | Number | Range | CBoolean;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}

	////maybe this should return a constrain? just syntactic sugar, desugaring to leftExp > value < rightExp
	//Range:
	//	lower=INT upper=INT;
	public RangeElements getRangeAccess() {
		return pRange;
	}
	
	public ParserRule getRangeRule() {
		return getRangeAccess().getRule();
	}

	//CString:
	//	value=EString;
	public CStringElements getCStringAccess() {
		return pCString;
	}
	
	public ParserRule getCStringRule() {
		return getCStringAccess().getRule();
	}

	//CBoolean:
	//	value=BOOLEAN;
	public CBooleanElements getCBooleanAccess() {
		return pCBoolean;
	}
	
	public ParserRule getCBooleanRule() {
		return getCBooleanAccess().getRule();
	}

	//Number:
	//	value=INT;
	public NumberElements getNumberAccess() {
		return pNumber;
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	//EString returns ecore::EString:
	//	ID | NULL;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	////('att' attributes+=Attribute ( "," attributes+=Attribute)* )?
	//Feature_Impl returns Feature:
	//	"Feature" name=EString (BEGIN subfeature+=Solitary subfeature+=Solitary* END)? ("[" constrains+=Constrain (","
	//	constrains+=Constrain)* "]")?;
	public Feature_ImplElements getFeature_ImplAccess() {
		return pFeature_Impl;
	}
	
	public ParserRule getFeature_ImplRule() {
		return getFeature_ImplAccess().getRule();
	}

	//Grouped:
	//	name=EString ("(" attributes+=Attribute ("," attributes+=Attribute)* ")")? ("[" constrains+=Constrain (","
	//	constrains+=Constrain)* "]")?;
	public GroupedElements getGroupedAccess() {
		return pGrouped;
	}
	
	public ParserRule getGroupedRule() {
		return getGroupedAccess().getRule();
	}

	//Mandatory:
	//	name=EString ("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")? ("[" constrains+=Constrain (","
	//	constrains+=Constrain)* "]")? (groups+=Group groups+=Group*)?;
	public MandatoryElements getMandatoryAccess() {
		return pMandatory;
	}
	
	public ParserRule getMandatoryRule() {
		return getMandatoryAccess().getRule();
	}

	//Optional:
	//	"?" name=EString ("{" subfeature+=Solitary ("," subfeature+=Solitary)* "}")? ("[" constrains+=Constrain (","
	//	constrains+=Constrain)* "]")? (groups+=Group groups+=Group*)?;
	public OptionalElements getOptionalAccess() {
		return pOptional;
	}
	
	public ParserRule getOptionalRule() {
		return getOptionalAccess().getRule();
	}

	//Or:
	//	"Or" name=EString (BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?;
	public OrElements getOrAccess() {
		return pOr;
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}

	//Xor:
	//	"Xor" name=EString (BEGIN grouped+=Grouped (","* grouped+=Grouped)* END)?;
	public XorElements getXorAccess() {
		return pXor;
	}
	
	public ParserRule getXorRule() {
		return getXorAccess().getRule();
	}

	//terminal NULL:
	//	"null";
	public TerminalRule getNULLRule() {
		return tNULL;
	} 

	//terminal BOOLEAN returns ecore::EBoolean:
	//	"true" | "false";
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	} 

	//// The following synthetic tokens are used for the indentation-aware blocks
	//// increase indentation
	//terminal BEGIN:
	//	"synthetic:BEGIN";
	public TerminalRule getBEGINRule() {
		return tBEGIN;
	} 

	//// decrease indentation
	//terminal END:
	//	"synthetic:END";
	public TerminalRule getENDRule() {
		return tEND;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
