/*
 * generated by Xtext
 */
package dk.itu.mdd.configurator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfUiModule extends dk.itu.mdd.configurator.ui.AbstractConfUiModule {
	public ConfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
