/*
 * generated by Xtext
 */
package dk.itu.mdd.configurator;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConfStandaloneSetup extends ConfStandaloneSetupGenerated{

	public static void doSetup() {
		new ConfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public Injector createInjectorAndDoEMFRegistration() {
               
		//dk.itu.mdd.configurator.PackageImpl.init(); 
		org.eclipse.xtext.common.TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}

}

