/*
 * generated by Xtext
 */
package dk.itu.mdd.configurator;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConfStandaloneSetup extends ConfStandaloneSetupGenerated{

	public static void doSetup() {
		new ConfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

