/*
 * generated by Xtext
 */
package dk.itu.mdd.configurator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfRuntimeModule extends dk.itu.mdd.configurator.AbstractConfRuntimeModule {

}
