/*
 * generated by Xtext
 */
package dk.itu.mdd.configurator.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.mdd.configurator.ui.internal.ConfActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConfExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConfActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConfActivator.getInstance().getInjector(ConfActivator.DK_ITU_MDD_CONFIGURATOR_CONF);
	}
	
}
