/*
 * generated by Xtext
 */
package dk.itu.mdd.configurator;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ConfUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return dk.itu.mdd.configurator.ui.internal.ConfActivator.getInstance().getInjector("dk.itu.mdd.configurator.Conf");
	}
	
}
