/**
 * generated by Xtext
 */
package dk.itu.mdd.configurator.validation;

import dk.itu.mdd.configurator.validation.AbstractConfValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ConfValidator extends AbstractConfValidator {
  public final static String INVALID_NAME = "invalidName";
  
  /* @Check
   */public Object featureStartsWithCapital(final /* Feature */Object feature) {
    throw new Error("Unresolved compilation problems:"
      + "\n! cannot be resolved."
      + "\nThe method warning is undefined for the type ConfValidator"
      + "\nThe method or field ModelMDD2Package is undefined for the type ConfValidator"
      + "\nLiterals cannot be resolved"
      + "\nNAMED_ELEMENT__NAME cannot be resolved");
  }
  
  /* @Check
   */public Object featureNameDifferentFromGroupName(final /* Group */Object it) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method error is undefined for the type ConfValidator"
      + "\nThe method or field ModelMDD2Package is undefined for the type ConfValidator"
      + "\n! cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nNAMED_ELEMENT__NAME cannot be resolved");
  }
  
  /* @Check
   */public Object featureNamesAreDistinct(final /* Group */Object it) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method error is undefined for the type ConfValidator"
      + "\nThe method or field ModelMDD2Package is undefined for the type ConfValidator"
      + "\n! cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nNAMED_ELEMENT__NAME cannot be resolved");
  }
  
  /* @Check
   */public Object typeCheck(final /* Binary */Object exp) {
    throw new Error("Unresolved compilation problems:"
      + "\n! cannot be resolved."
      + "\nThe method error is undefined for the type ConfValidator"
      + "\nThe method or field ModelMDD2Package is undefined for the type ConfValidator"
      + "\nLiterals cannot be resolved"
      + "\nNAMED_ELEMENT__NAME cannot be resolved");
  }
}
