/**
 * generated by Xtext
 */
package dk.itu.mdd.configurator.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ConfScopeProvider /* implements org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider  */{
}
