/**
 * generated by Xtext
 */
package dk.itu.mdd.configurator.ui.contentassist;

import dk.itu.mdd.configurator.ui.contentassist.AbstractConfProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ConfProposalProvider extends AbstractConfProposalProvider {
}
